### ISSUE TITLE
Yolov3-Tensorflow to trt model and run in Xavier NX

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [jkjung-avt/tf_trt_models#12]
Hi Sir, 
           I have a Yolov3 Tensorflow implemented model, now I have weights in both .ckpt and .pb. 

How I can convert these weights to .trt after optimization? I have tried for several days but failed to find any hint.

**Comment by jkjung-avt** [comment]
If you want to do TF-TRT, you could load the pb and then just call trt.create_inference_graph() to optimize it, as done [here](https://github.com/jkjung-avt/tf_trt_models/blob/master/utils/od_utils.py#L57).

If you'd like to convert it to a pure TensorRT engine, you need to convert the pb to either onnx or uff first.  You could find some examples about how to do that in my [tensorrt_demos](https://github.com/jkjung-avt/tensorrt_demos) repository.  I myself haven't tried to convert a tensorflow yolov3 model to TensorRT engine before.  But in case you could convert your model to darknet format (cfg/weights) first, then you'd likely to be able to use my [tensorrt_demos](https://github.com/jkjung-avt/tensorrt_demos) code optimize the model directly.

**Comment by MuhammadAsadJaved** [comment]
OK. Thank you for your reply sir. I'll give it a try.

**Comment by MuhammadAsadJaved** [comment]
@jkjung-avt Sir for the  trt_create_interface_graph()   What should be the  output_names in the "output = output_names"

```
    trt_graph_def = trt.create_inference_graph(
        input_graph_def=frozen_graph_def,
        outputs=output_names,
        max_batch_size=1,
        max_workspace_size_bytes=1 << 26,
        precision_mode='FP16',
        minimum_segment_size=50
    )
    with open(pb_path, 'wb') as pf:
        pf.write(trt_graph_def.SerializeToString())

```

**Comment by jkjung-avt** [comment]
> What should be the output_names in the "output = output_names"

It should be the list of **output tensor names** of your model.  You should know that when you build your tensorflow graph.

For example, the output tensor names of tensorflow SSD models are: [ 'detection_boxes', 'detection_classes', 'detection_scores', 'num_detections' ]

https://github.com/jkjung-avt/tf_trt_models/blob/master/tf_trt_models/detection.py#L188

https://github.com/jkjung-avt/tf_trt_models/blob/master/tf_trt_models/detection.py#L21-L25

**Comment by MuhammadAsadJaved** [comment]
Hi Sir,  @jkjung-avt 

 I have an optimized frozen graph (model.pb) with TF-TRT to (model-TRT.pb). But the speed of the model and size of the model is the same. 
I have checked the number of nodes in both models and TRT model contains slightly fewer nodes. 
But the model size and speed is still same? 

Please can you review this example, am I doing any mistake? 

![Screenshot from 2020-09-28 12-14-27](https://user-images.githubusercontent.com/28862708/94396941-8222b680-0195-11eb-9445-f02375fc178b.png)

**Comment by jkjung-avt** [comment]
@MuhammadAsadJaved  I'm not able to spot any problem.  I'd suggest you to post the question onto [NVIDIA developer forum](https://forums.developer.nvidia.com/c/agx-autonomous-machines/jetson-embedded-systems/jetson-xavier-nx/258).

**Comment by MuhammadAsadJaved** [comment]
@jkjung-avt  OK sir. Thank you so much for your cooperation.
