### ISSUE TITLE
How to run faster_rcnn_inception_v2 trained object detection tensorflow model on Jetson tx2?

### ISSUE THREAD

**Issue by spurani** [jkjung-avt/tf_trt_models#13]
Hi I have successfully configured tf_trt_models according to your posted guide and tensorflow successfully. I am able to import both tensorflow and tf_trt_models in python3 module on Jetson Tx2. I have faster_rcnn_inception_v2 trained object detection tensorflow model but I am getting following error when I am building the tf_trt_model with camera.py it throws me this error. Can you please guide me? it would be really helpful for me to learn new concepts. Thanks

`InvalidArgumentError: node BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/Slice (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748)  has inputs from different frames. The input node BatchMultiClassNonMaxSuppression/map/while/Reshape_1 (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748)  is in frame 'BatchMultiClassNonMaxSuppression/map/while/while_context'. The input node BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/Slice/begin (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748)  is in frame ''.`

**Comment by jkjung-avt** [comment]
I don't know what this "InvalidArgumentError" is about.  I think you should post the question to NVIDIA Developer forum and seek answers there...
